[tool.poetry]
name = "open-cctv5"
version = "0.1.0"
description = ""
authors = ["liuxzzz <691381755@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
